# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('segmento', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nome_atendente', models.CharField(max_length=255)),
            ],
        ),
    ]
