# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('und_medida', models.CharField(max_length=255)),
                ('custo', models.CharField(max_length=255)),
                ('validade', models.CharField(max_length=255)),
                ('qtd_estoque', models.CharField(max_length=255)),
                ('classe_tipo_produto', models.CharField(choices=[('estocavel', 'Estoc\xe1vel'), ('n_estocavel', 'N\xe3o estoc\xe1vel'), ('cons_geral', 'Consumo geral'), ('manutencao', 'Manuten\xe7\xe3o')], max_length=1)),
            ],
        ),
    ]
