# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_auto_20180322_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='observacao',
            field=models.TextField(default='', max_length=400),
        ),
    ]
