# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_auto_20180322_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Relat\xf3rio',
                'verbose_name_plural': 'Relat\xf3rios',
            },
        ),
    ]
