# -*- coding: utf-8 -*-
# Generated by Django 2.0.3 on 2018-03-27 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0008_auto_20180327_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('estocavel', 'Estocável'), ('n_estocavel', 'Não estocável'), ('cons_geral', 'Consumo geral'), ('manutencao', 'Manutenção')], max_length=255)),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.UnidadeMedida')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='unidade_medida',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
