# Generated by Django 2.0.3 on 2018-04-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0011_auto_20180330_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='nota_Fiscal',
            new_name='nota_fiscal',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='itens',
        ),
        migrations.AddField(
            model_name='itementrada',
            name='entrada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.Entrada'),
            preserve_default=False,
        ),
    ]
