# Generated by Django 2.0.5 on 2018-05-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0014_auto_20180509_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'verbose_name_plural': 'Entrada de material'},
        ),
        migrations.AlterModelOptions(
            name='itemsaida',
            options={'verbose_name_plural': 'Saída de material'},
        ),
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={'verbose_name_plural': 'Pessoa fisica'},
        ),
        migrations.AlterModelOptions(
            name='saida',
            options={'verbose_name_plural': 'Histórico de saída'},
        ),
        migrations.RemoveField(
            model_name='saida',
            name='data',
        ),
        migrations.AlterField(
            model_name='saida',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
