# Generated by Django 2.0.5 on 2018-05-15 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0016_saida_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'verbose_name_plural': 'Entrada de Material'},
        ),
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={'verbose_name_plural': 'Pessoa Física'},
        ),
        migrations.AlterModelOptions(
            name='saida',
            options={'verbose_name_plural': 'Saída de material'},
        ),
        migrations.AlterField(
            model_name='saida',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saida_solicitante', to='almoxarifado.PessoaFisica'),
        ),
    ]
