# Generated by Django 2.0.5 on 2018-05-15 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0017_auto_20180515_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=8)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.Material', unique=True)),
            ],
        ),
    ]
