# Generated by Django 2.0.5 on 2018-10-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0019_auto_20180515_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Setor',
            },
        ),
        migrations.AlterField(
            model_name='saida',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saida_solicitante', to='almoxarifado.Setor'),
        ),
        migrations.DeleteModel(
            name='PessoaFisica',
        ),
    ]
